name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: rust:1.79

    services:
      nats:
        image: nats
        options: --network-alias nats

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
      env:
        NATS_URL: "nats:4222"
    - name: Run tests
      run: cargo test --verbose
      env:
        NATS_URL: "nats:4222"
